# Generated by Django 4.1.7 on 2023-07-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='message',
            field=models.TextField(max_length=250),
        ),
    ]
